### ISSUE TITLE
Arranging over six items in the hand window

### ISSUE THREAD

**Issue by Horus2** [prkc/lost-bazaar#35]
In case a player has more than six items in hand and has to scroll down with the white arrows, the algorythm starts to arrange items in an unfathomable order, sometimes causing items on the previous page reappearing a second time. Furthermore it may also cause truncated item pictures of few pixel heights to appear, which are not belonging to an actual entity.

**Comment by prkc** [comment]
seems to work fine here / needs precise instructions on how to reproduce
