### ISSUE TITLE
Orphaned Bomb pictures

### ISSUE THREAD

**Issue by Horus2** [prkc/lost-bazaar#38]
Upon the detonation of a Bomb by a condition that is outside an event, floating orphaned images of the item picture and the points (staying on the tile it was) remain, accompanied by a fullscale card illustration at (-1; -1) coordinates.
In the current state of the Bomb, the condition outside the events checks only for the safety of the Bomb; thus it detonated in the moment it leaves this condition, even if it has counters on it, so it is easy to reproduce.

**Comment by prkc** [comment]
All Bomb-related discussion moved to Issue #37
