### ISSUE TITLE
No resetting of cards between matches

### ISSUE THREAD

**Issue by Horus2** [prkc/lost-bazaar#40]
Upon starting a second new game without quitting from the application, remnants of the data from the previous match makes it unplayably buggy: cards in hand not being displayed, point and cardcount indicator shows false values, items in trash at the start, and so on. We need to locate all the occuring bugs before it gets too labyrinthine with to the upcoming features.

**Comment by prkc** [comment]
Bugs mentioned in the OP are now fixed, all related bugs should be added to Issue #23
