### ISSUE TITLE
Text of the abilities on cards is off

### ISSUE THREAD

**Issue by Horus2** [prkc/lost-bazaar#45]
On certain cards, the first two pixels wide line of the text box is left empty/white, and/or the text covers a  two pixels wide line of the lower part of the frame.
Examples being (with hungarian texts):
Stamp - 2 pixels
Padlock - 2 pixels
Vase - Top 2 pixels line missing, covers 2 pixels line of the border on the bottom
Snooker ball - actually wider by 2 pixels on top and narrower by 2 on the bottom
Tricky die - is like the Snooker ball

In the case of the Net, the horizontal separator bar between the abilities is missing/white.

At roughly half of the cards it works as it should (Broom, Hammer, Souvenir, Lace fan etc.)

**Comment by prkc** [comment]
fixed
